### ISSUE TITLE
Primary Challenge landing page

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#1]
As a competitor, I want to see the most useful information front and center, so that I can efficiently check my and my team's standings.

Acceptance criteria:
- landing page contains the following information:
   - TBD

**Comment by scottpdawson** [comment]
![wireframe](https://user-images.githubusercontent.com/5529897/98490542-c62ac180-21ff-11eb-804e-f60aa8d58dfe.jpg)

**Comment by adamengst** [comment]
Should the races go vertically, with the top three competitors in each category running horizontally? That way there will be more vertical scrolling than horizontal scrolling. I always feel that horizontal scrolling is weirder and more confusing.

**Comment by scottpdawson** [comment]
@adamengst I think you're right! It'll be easy to transpose this when the page is coded, but as a matrix I think it works well regardless of orientation. So yes, races vertically, categories horizontally. The grid framework will let me pin the first column so as you scroll horizontally to view categories, the race name remains visible.

**Comment by adamengst** [comment]
OK, let's fill this one out for real:

As a competitor, I want to see a summary of the top results for every race and the series as a whole so I can tell where I and my team are in the standings.

Acceptance criteria:

The landing page should include:

- The FLRC Challenge logo
- A link to a static page on the FLRC site with full details and rules
- The top three men and top three women who have the most points in the Challenge overall. 
- The top three individuals (regardless of sex) who have the most miles run in the Challenge overall.
- The top three teams by lowest score (cross country scoring)
- For each race, the top three in each of these categories:
  * Fastest men
  * Fastest women
  * Best average time for men
  * Best average time for women
  * Top teams by age-grading
  * Top teams by most efforts
- Links to detail pages for each of the above

**Comment by stevedesmond-ca** [comment]
Implemented as of 714457f

As mentioned in the forum, layout/design is not final and performance needs improvement, but the data should all be there and correct now
