### ISSUE TITLE
Calculating team points

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#10]
As a member of a team, I'll be curious how my team ranks against other teams in the two contests—average age-grade for the top 10 runners on the team and most efforts for the entire team—and in the combined score.

Acceptance criteria:
* Average age-grade shall be calculated by taking the average of the top 10 unique (by runner) results for that team, and averaging the age-grade for each result. (In other words, if one runner has multiple results in the top 10, we only look at the fastest one.)
* Most efforts shall be calculated by simply summing the total number of efforts across all team members.
* For each race, each team will get 1 to 7 points, with 1 point for being in first place (best) for each of the age-grade and most efforts contests. Second place gets 2 points, and so on. So for each race, each team will end up with 2 to 14 points.
* For the challenge as a whole, those points will be added up for all 10 races, with each team having between 20 and 140 points.
* Like cross-country scoring, lowest number of points wins.

**Comment by stevedesmond-ca** [comment]
Before I forget again, since I keep forgetting: what to do with runners whose birthday next year would have them switch teams? e.g. runner turns 30 on July 1, 2021: do they go in the 20s or 30s?

**Comment by stevedesmond-ca** [comment]
Should runners under 20 go in the 20s team, or no team for them? Same with the off-chance of someone 80+?

**Comment by adamengst** [comment]
Ach, sorry, missed the notification on this. At the moment, I have a 1-19 age group that could be a team, so let's leave them as their own team for now. (If it turns out we get only a couple of runners in it, we could move them up to the 20-29 team later). The final age group and thus team is 70+, so that should take care of the 80s and up if there are any.

**Comment by stevedesmond-ca** [comment]
Implemented as of 2443630
