### ISSUE TITLE
Overall Challenge points page for male individuals

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#11]
As an individual male competitor, I want to see where I am in the overall Challenge points competition:

Acceptance criteria:
* The page should show a list of all male runners in the Challenge, with rank, name, age, and points.
* The list should be sorted by points, with the largest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort).

Note that Webscorer allows runners to select Other for gender. Those who select Other should fall out of both the male and female standings.

**Comment by stevedesmond-ca** [comment]
"fall out of" = be included or excluded?

**Comment by adamengst** [comment]
"be excluded" 

Some background. From what we gather from researching the topic, most non-binary people don't want attention drawn to themselves or to the fact that they're non-binary. What with all the possibilities for non-binary, the club's general thinking is that we should just not make a fuss about them in any way right now. They can run, and if they are in a competition where sex doesn't come into play (the most efforts category for the Challenge), that's fine, but they should just be excluded from any sex-based results or awards.

**Comment by adamengst** [comment]
To clarify this further, for the calculation of overall points, we want to take each runner's best effort on each course and add that up. That way, it's clear that there's never a penalty for running a course slowly.

**Comment by stevedesmond-ca** [comment]
Implemented as of ed2d321
