### ISSUE TITLE
Overall Challenge standings page for teams

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#12]
As a member of a team, I want to see where my team ranks in the overall Challenge.

Acceptance criteria:
* The page should show all seven teams, with team name, age-grade point, most effort points, and total points.
* The list should be sorted by total points, with the largest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort).

**Comment by stevedesmond-ca** [comment]
Looks like there's a discrepancy here between higher points being better here vs lower on #6. I think higher being better makes sense, especially early on when certain teams won't have full results for all courses yet.

**Comment by stevedesmond-ca** [comment]
Same w/ #10

**Comment by adamengst** [comment]
Good catch—this was a mistake. Because we're doing cross-country scoring, where the lowest number of points wins, we'll want to sort this with the SMALLEST number at the top. 

As for what to do before teams have results for all courses, what do you think about awarding 7 points for uncompleted courses (for both age-graded and most efforts)? That way every team would in essence start with 14 points until at least one person ran the course for the team.

**Comment by stevedesmond-ca** [comment]
Yep, that makes sense and should be fairly easily doable

**Comment by stevedesmond-ca** [comment]
Implemented as of 0d6243a
