### ISSUE TITLE
Overall Challenge points page for female individuals

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#13]
As an individual female competitor, I want to see where I am in the overall Challenge points competition:

Acceptance criteria:
* The page should show a list of all female runners in the Challenge, with rank, name, age, and points.
* The list should be sorted by points, with the largest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort).

Note that Webscorer allows runners to select Other for gender. Those who select Other should fall out of both the male and female standings.

**Comment by stevedesmond-ca** [comment]
Where total points are just the sum of their points for each course?

**Comment by adamengst** [comment]
Yes, that's correct. Every runner will have points for every race, and for the overall Challenge, we're just summing them. Those who don't run as many races won't do as well, of course, and the faster runners will do better than the slower ones.

**Comment by adamengst** [comment]
So I'm rethinking this, and am curious what others think. Initially, I was thinking of summing all points across all efforts. But if we do that, someone who is very slow but runs a short course lots of times could easily win, which doesn't seem like the desired effect. Now I'm thinking that we should take each runner's best effort on each course and add that up. That way, it's clear that there's never a penalty for running a course slowly.

**Comment by stevedesmond-ca** [comment]
Implemented as of ed2d321
