### ISSUE TITLE
Most efforts for individuals not showing on main page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#16]
We'll also want a top-three table for Most Efforts for each race on the main leaderboard page. We only need one, I think, since most efforts isn't a gendered competition.

**Comment by stevedesmond-ca** [comment]
In addition to "most miles" from #1, or instead of?

**Comment by stevedesmond-ca** [comment]
Should we remove the M/F filters for the most runs tab in the course results view?

**Comment by adamengst** [comment]
Yes, #1 was incomplete now that I look at it. Sorry! The three individual competitions are fastest, best average, and most efforts, so we'll want to display all three when summarizing a race.

As far as the M/F filters for the Most Runs tab, let's leave it. It's not really relevant for the race results, but it does let people dive into the data in a potentially interesting way.

**Comment by stevedesmond-ca** [comment]
Sorry, looks like the notification got sent before I deleted my original comment. Just to clarify: this top 3 is only at the per-race level, the corresponding overall competition is "most miles"?

**Comment by stevedesmond-ca** [comment]
OK, now I'm confused because I can't find this "Most Miles" issue I was just talking about...

**Comment by stevedesmond-ca** [comment]
Found it hidden in https://github.com/FingerLakesRunnersClub/ChallengeDashboard/issues/1#issuecomment-731848975

**Comment by adamengst** [comment]
Yes, to confirm, each race should have most efforts, and the overall Challenge competition would be for most miles.

**Comment by stevedesmond-ca** [comment]
Implemented as of 44401a7

(Leaderboard definitely needs an overhaul now, I'll see if I can get my idea working by this weekend)
