### ISSUE TITLE
Age grade sorting is wrong in some places

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#17]
If you look at the Thom B results for men and sort by Age Grade, a 9.67 sorts above a 66.92. That guy's time is really weird and possibly wrong too (6 hours?) so it's possible the problem is in the data rather than the calculation.

https://flrc.azurewebsites.net/Course/178952/Fastest/M

Also, with the Black Diamond Trail using Lucifer's Crossing results, we end up with an age grade above 100%, presumably because the runner's time was faster than the world record for 10 miles (it being only a 6 mile course). It sorts weirdly too.

https://flrc.azurewebsites.net/Course/203895/Fastest/M

**Comment by stevedesmond-ca** [comment]
Good catch, I hadn't checked all the sorts for all the races yet -- same
thing will happen if someone gets less than 20 points on a course, and I'm
guessing since funkiness around courses that have some results both above
and below the 1h mark. I'll take care of this all tonight.

**Comment by stevedesmond-ca** [comment]
Fixed as of df87582

Side note: the 6 hour time is because it's the 52K of Thom B (WebScorer doesn't filter API responses for races with multiple distances)
