### ISSUE TITLE
Fastest results per age group

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#19]
@adamengst Are we going to want to display separate tables for each age group somewhere? Or is sorting by team and looking at the results that way good enough?

I think the easiest way to do this would be to have a similar button bar to the All/F/M -- quick mock up:
![image](https://user-images.githubusercontent.com/195896/102945714-8c9ad680-448c-11eb-9f6d-37399f5b2924.png)

Admittedly, that's starting to look a little busy/complex.

**Comment by adamengst** [comment]
My initial thinking was that sorting by team and scanning would be sufficient, and it does seem to be doing the right thing in terms of keeping the previous ranking in place inside the team grouping...

But that said, and this may be a design question for @scottpdawson, it would be more obvious to provide the button bar. Spacing it out a bit more, or tweaking the visual design slightly could reduce the busy/complex feeling.

**Comment by stevedesmond-ca** [comment]
Now that we have the possibility for someone to score in multiple age groups (assuming we still want to do that?) we'll definitely need to display age group filtered results, since the All/F/M views only show the single best result per person.

I think the rules will need something specific about how exactly ages and teams are determined, since seeing someone in the 20-29 team but having an age of 30 would probably raise some eyebrows.

**Comment by adamengst** [comment]
Good point—I hadn't thought about the edge case of someone scoring in multiple age groups in this context, but yes, I think it still makes sense to do that.

I have a to-do item to write up the rules very carefully, and will be sure to run them by folks here to make sure we sync up. :-)

**Comment by scottpdawson** [comment]
Perhaps instead of a button bar select lists would be a better option, since you can't multi-select anyway. Would reduce the visual complexity.

**Comment by adamengst** [comment]
I was thinking that too but didn't say anything to avoid biasing decisions. :-)

**Comment by stevedesmond-ca** [comment]
Implemented as of 0200912

The addition of age group filtering does make a potential confusion around the "Points" column more obvious.

Points are currently relative to the results being calculated (just like "Rank"), so if we're looking at results for only a single age group, the leader of that age group shows as 100 points there, where they may have less in the "real" (overall points) competition. Similarly/conversely, the fastest F runner, if not the fastest overall, will be shown as less than 100 when looking at combined results, but 100 when looking at F only.

The overall points calculations are using the correct values, but the results being displayed are not always the values used for that competition. This may be something we want to clarify in the detailed rules, or even hide the column unless looking at all age groups for a single M/F category (the only place points really matter/exist).

Thoughts?

**Comment by adamengst** [comment]
I see what you mean. I think the most elegant solution would be to hide the Points column unless it's showing all age groups in either M or F (not All). That way it's present if you need to see how many points you got for a certain race, but it's never showing a point value that could be confusing.

**Comment by stevedesmond-ca** [comment]
Implemented as of 58ff0d1

**Comment by adamengst** [comment]
Just to confirm, @stevedesmond-ca, are we showing each runner's current age throughout the year? (Which will change for everyone, and will cause some people to jump age groups.)

The unavoidable downside of that is that people who jump age groups will show a "wrong" age with respect to their team (which was set as of January 1st), but it's otherwise much better and more consistent to display the runner's current age for age-group sorting and filtering reasons.

**Comment by stevedesmond-ca** [comment]
For the "fastest" results, the age shown is their age as of the run being used for the result (e.g. the day they ran their fastest time). For best average and most runs, it's using their Jan 1 age, so that their runs throughout the year don't get split between their 2 ages.

It's definitely possible to update it to show their age as of the current day (e.g. age bumps up everywhere it's displayed on their birthday) but still use their "run day" age for things like age grade calculations. I do think that might cause some additional confusion around things like age group results when people jump age groups, (why is this 50yo showing in the 40-49 results?) or if someone tries to verify an age grade but the age doesn't match.

Swinging the pendulum back in the other direction, other than the possibility of winning multiple age group awards, the simplest thing would be to say "your age on X day (e.g. Jan 1) is your age used throughout the event" but I don't know if that multiple age groups thing is a dealbreaker.

Does any of the above sway you in one direction or another? It's always fun trying to balance intuition and complexity in non-trivial problems like this!

**Comment by adamengst** [comment]
Yeah, it's a fascinating question, since there's no way to satisfy all the possibilities... I honestly can't predict how people might or might not get most confused, so let's leave it like it is now, and we can revisit later in the year once we have real results to react to and once we field questions from the runners.
