### ISSUE TITLE
Leaderboard biased against Engsts :-)

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#20]
The athlete pages for both me and Tonya seem to be broken, though everyone else's are working fine. I suspect it has to do with weird data given our testing. Yes... the Dec22 Test and Dec14 Test users are also broken, although the Steve Desmond user works.

https://flrc.azurewebsites.net/Athlete/Index/6728
https://flrc.azurewebsites.net/Athlete/Index/36492

![image](https://user-images.githubusercontent.com/36641103/103012376-8139c080-4509-11eb-96f8-69d9934bddfd.png)

**Comment by adamengst** [comment]
I'm thinking whatever is causing this problem may also be blocking some new results I've posted to FLRC Challenge Test 1 from appearing. I added three new results there to see what it would look like.

**Comment by stevedesmond-ca** [comment]
Hmm, I'm seeing 5 runs for you in the API, and 5 runs on the course results page for [Most Runs](https://flrc.azurewebsites.net/Course/229586/MostRuns/M)...were you expecting something different?

I do see the crash on your athlete page (and some others, but not everyone :unamused:) -- something funky happening with showing the average...will check it out tonight!

**Comment by adamengst** [comment]
My mistake—because I have two users showing up, I was fixated on seeing my name occur more often in the list, rather than looking at the Most Runs number. So cancel that concern—data is coming through right!

**Comment by stevedesmond-ca** [comment]
:dizzy_face: That was a doozy to figure out -- it wasn't catching the case where someone didn't have enough runs on a given course to reach the threshold to be included on the list.

Fix incoming!

**Comment by adamengst** [comment]
Looks good to me—I'll let you close, since I'm not sure of who should do what, but I can confirm that all the users who were failing are now working. Thanks!

**Comment by stevedesmond-ca** [comment]
Implemented as of b2aafcb
