### ISSUE TITLE
Display All Runs as a sortable table rather than a disclosure list

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#21]
The leaderboard has a nice disclosure triangle hiding the full results under All Runs, but thinking about this as a runner, I think I'd want to be able to see where today's run fits into my overall set of efforts. With All Runs, I'd have to scan through the entire list and mentally sort and order things. 

If All Runs (for each course, per athlete) could be its own page, the runner would be able to see at a glance (or with a quick click to sort) just how they're progressing. The fields that would make sense to me would be:

* Rank
* Date
* Time
* Age Grade

**Comment by stevedesmond-ca** [comment]
This one will likely need to be a post-launch enhancement, as it will require a fundamental shift in how those tables are rendered, which is currently limited technically to one per page.

**Comment by adamengst** [comment]
Oh, sorry, yes, one per page. If you run a course 20+ times, anything other than one per page will get unwieldy very quickly.

**Comment by stevedesmond-ca** [comment]
Implemented as of 5eb99ff
