### ISSUE TITLE
Leaderboard should display equal ranks for ties

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#22]
As someone with the same number of efforts on a course as the leader, I want my rank to be equal to theirs, so that it doesn't seem like the system is arbitrarily picking a winner.

Acceptance criteria:
- Leaderboard tables show equal ranks for equal values

Implementation notes:
- this would be fairly straightforward if it weren't for the team results, so this will probably require a fairly large refactoring

**Comment by adamengst** [comment]
Looks like this is working now, such as at https://flrc.azurewebsites.net/Course/228617/MostRuns

**Comment by stevedesmond-ca** [comment]
Works everywhere except the front page, this is my reminder to need to fix that :sweat_smile:

**Comment by stevedesmond-ca** [comment]
Fixed for individuals as of 99f1eca, but teams will require quite a bit of refactoring

**Comment by stevedesmond-ca** [comment]
Implemented as of 9af7422
