### ISSUE TITLE
Team overview page

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#26]
As a team player, I want to see an overview of how my team is doing (both overall and for each course), so I know where to best focus my attention.

Acceptance criteria:
- similar to individual athletes, clicking on a team name will link to a page containing the following information:
  - age grade points and rank
  - most runs points and rank
  - total team points and rank
  - a link to the overall team points page
  - for each course:
    - average age grade for top 10 runners and rank
    - total runs and rank
    - total points and rank
    - a link to the team results for that course

**Comment by adamengst** [comment]
Yes! Good thinking.

**Comment by stevedesmond-ca** [comment]
Implemented as of dae982e
