### ISSUE TITLE
Team standings on main leaderboard page should show overall points as well as fastest/most runs

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#27]
As a team player, I want to see at a glance how my team is doing on different courses. Right now, we can see the team rankings on the main page for fastest age-graded times and most runs, but not the combination of the two, which is what really matters.

Acceptance criteria:
* Display a third table for each course showing
  * Rank, team name, and total points

I think this will actually improve the visual look a little, since both team and F/M displays on the main page will have three tables for each course, so more consistency.

**Comment by stevedesmond-ca** [comment]
Implemented as of 2b4dc9e
