### ISSUE TITLE
Significant digits in times and distances

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#28]
As a geek, while I appreciate precision, it isn't helpful to have too much of it in the results. 

Acceptance criteria:
* Distances for team total runs on course pages should be rounded to one significant decimal place, so 34.999999999 should be 35. :-)

![image](https://user-images.githubusercontent.com/36641103/103369591-8c0bcc80-4a98-11eb-855d-318cd55e0d4e.png)

* For all time reports, we should follow USATF rules, which stipulate that all times that are not even seconds should be rounded up to the next even second. That way we're just displaying hours, minutes, and seconds.

> For races partly or entirely outside the stadium, unless the time is an exact whole second, the time shall be converted and recorded to the next longer whole second, e.g., 2:09:44.3 shall be recorded as 2:09:45.

**Comment by stevedesmond-ca** [comment]
lol I'm surprised a floating point display bug didn't get through sooner 🙈

The `RaceTime` we get from the WebScorer API goes to thousandths, do we keep that for finer-grained ranking and just display rounded? e.g. 4:39.001 vs 4:39.999...does the first one win, and we're just rounding up when displaying results? Or is that considered a tie?

**Comment by adamengst** [comment]
I think we need to round up and consider everything that's the same seconds as a tie. The problem is that the Webscorer precision doesn't match to accuracy; it's just random extra digits that don't really mean anything.

**Comment by stevedesmond-ca** [comment]
😅 just making sure you hadn't changed your mind on the duathlon (running + QR scanning) suggestion

**Comment by adamengst** [comment]
The transition time is what kills you. :-)

**Comment by stevedesmond-ca** [comment]
Implemented as of eb3d703
