### ISSUE TITLE
Ignore too-fast times when loading results

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#29]
As the race director, I don't want people submitting mistaken times that are ridiculously fast and thus confusing all the results until we figure out what has happened. 

Acceptance criteria:
* Initially, let's just ignore all times under 4:00—no course can possibly be run in that time. 
* Further out, we may need a per-course minimum to eliminate the possibility of someone getting slightly lost or cutting the course and running a too-fast time (perhaps without even realizing) that's well above the 4:00 cutoff.

**Comment by stevedesmond-ca** [comment]
Implemented as of 14a38d6
