### ISSUE TITLE
Per-race fastest average time results page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#3]
As a not-so-speedy competitor, I want to be able to check my standing against other competitors for fastest average time.

Acceptance criteria:
- The results list should include rank, name, age, team, average time, time back from leader, and number of efforts.
- The time listed for each runner should be their average (mean) time across the runner's top times for the average number of efforts.
- The list should include all runners who have completed the course a minimum of the average (mean) number of efforts.
- The page should display what the current average number of efforts is, so people can see what they have to aim for.
- The list should be sorted by fastest average time, with the largest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort).

**Comment by adamengst** [comment]
Just updated this one to note that the average should be calculated from the runner's top X times, where X is the average (mean) number of efforts for any runner in the race. Here's why. If we calculate the average across all of a runner's efforts, they're actively dissuaded from running a course slowly, perhaps with a friend or just for an easy run. That's not ideal—we want to encourage as much running as reasonable. 

I also thought about calculating it across the top 10 times, say, but having that X be a fixed number would mean that people would aim for it and then potentially stop. By having X float up as the average number of efforts increases, it still encourages people to run more (increasing the average and adding to their effort count) even when they're running slowly.

**Comment by stevedesmond-ca** [comment]
Yep, that makes sense. I'm interpreting X to be the ceiling of the mean (or the mean rounded up to the next whole number).

e.g. 2 runners run once, 1 runs twice, one runs 3 times; mean is 7/4=1.75, which we round up to 2 and only show runners who have run at least twice, averaging their top 2 times.

**Comment by adamengst** [comment]
Yes, I think that's spot on.

**Comment by stevedesmond-ca** [comment]
Is the minimum number of runs gender-specific? e.g. M could need to run at least 3 times (and their top 3 times are considered) based on their average, but F only 2? Should the combined results page use the combined average minimum requirement?

**Comment by adamengst** [comment]
Hmm, good question. My initial reaction was to say that gender doesn't matter, but in fact, I think it does. Otherwise, we could end up with a situation where a woman drives the average way up by running a ton of efforts and then no men actually meet the minimum number to qualify at all. 

So yes, the average number of efforts should be gender-specific when calculating the minimum number of efforts required and the number of efforts to include. And should be reported separately so people know what they have to do.

**Comment by stevedesmond-ca** [comment]
Implemented as of db46b58
