### ISSUE TITLE
For Teams on main page, change "Fastest" label 

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#31]
As someone who's unfamiliar with age grading, the term "Fastest" on the main leaderboard page for teams at https://challenge.fingerlakesrunners.org/ is confusing, since it's accompanied by a percentage. I'm not quite sure what fits best, but on the internal team pages, we use "Average Age Grade" and it's probably best to stay consistent. If that doesn't fit, "Age Grade" would be fine.

Acceptance criteria:
* "Fastest" label on main leaderboard page for teams changes to "Age Grade"

**Comment by stevedesmond-ca** [comment]
Implemented as of cc41aad
