### ISSUE TITLE
Most Runs option in Overall Leaders screen

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#33]
As the race director, I need to award prizes to the top 10 runners who complete all 10 courses, sorted by average age-graded time. (The goal here is to acknowledge the people who do well across the entire series, but just aren't the fastest man or woman.)

Acceptance criteria:
* A Most Runs button on the Overall Leaders screen would show, for all participants in the series:
  * Rank, Name, Age, Number of Runs, Average Age-Grade
  * Sorting should be by number of runs first and age-grading second
  * Because it's age-graded, there's no gender-filtering needed

(Sorry for forgetting this earlier! I'm writing up the public-facing prizes and rules now, which triggered this realization.)

**Comment by adamengst** [comment]
I don't think that this needs a top-level top in the Overall Leaders section, at least to start, since it only gets interesting once people have all 10 courses completed. And that would give us five tables in that area, which would be awkward. :-)

**Comment by stevedesmond-ca** [comment]
Is this in addition to the "Most Miles", or should we tweak "Most Miles" to only show runners who have completed all 10 and include the average age grade? Just making sure it's an explicit decision for both the East Hill Rec Way mile and the Skunk Cabbage HM to count as 1 run!

**Comment by adamengst** [comment]
Good thinking. Tweaking Most Miles would also work. We'd need to add the Average Age-Grade column, and what I realized is of course not "Number of Runs" but "Courses Completed." We'd still want to include people who haven't completed all 10 so everyone could see who's close (or nowhere near).

I also realized that the other reason for this information is because I need a list of everyone who has completed all 10 courses and thus gets an FLRC Challenge medal at the end of the year.

**Comment by stevedesmond-ca** [comment]
:100: this all makes much more sense now!

**Comment by stevedesmond-ca** [comment]
I think for consistency, if these are their own award/competition (separate from "most miles", they should have their own table -- what are your thoughts on moving the leaderboard M/F/Team filter to the top, and filtering the "Overall" top 3s, so that this shows on the M/F leaderboards, but we can keep the number of columns constrained?

**Comment by stevedesmond-ca** [comment]
Implemented as of bed4b1e

Let me know what you think about the 5 overall leaders tables -- the filter idea didn't end up making too much sense (at least compared to the course results) since there's only 1 team competition and 1 gender-specific competition.

**Comment by adamengst** [comment]
I agree that this is best as its own table, as you've done, and the five overall leaders tables work for me as well—the filter would have felt awkward because the goal is to see all this stuff at a glance.

Man, I am so dying to see real data appearing here. :-) Soon!

**Comment by adamengst** [comment]
You know, after looking at it and using it a bit more today, I think the one tweak I'd suggest is to put the two Most Points tables on the top, since they're the big bananas of the overall competition and should come first. Then the team and age grade and most miles tables can be underneath them.
