### ISSUE TITLE
Rename "Forest Frolic Trail Run" to "Forest Frolic"

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#38]
I decided it was inconsistent since we didn't have "Trail Run" after Tortoise & Hare or Danby Down & Dirty. I left it in the name of "Thom B. Trail Run" because "Thom B." is just too inscrutable on its own.

**Comment by stevedesmond-ca** [comment]
Implemented as of 112d506

**Comment by adamengst** [comment]
Ach, sorry to open this again but I've now also changed the name of the page on the FLRC site and the URL, which is now

    https://fingerlakesrunners.org/challenge/forest-frolic/

If you could fix the link in the leaderboard too, that would be great.

It's my consistency hobgoblin... :-)

**Comment by stevedesmond-ca** [comment]
:sweat_smile: I noticed that and checked the URL when I made the name change -- not a big deal, fixed now! 74fe76f
