### ISSUE TITLE
Team average age-grading calculation correct?

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#39]
As a competitor, it seems that the 50-59 team's average age grade looks wrong at the moment. At the moment, there are only two runners, Sean and me, and our individual best efforts are a 77.36% for Sean and 75.86% for me. So I'd expect a team average age grade of 76.61% given that those are our best efforts and we're the top "10" runners on the team right now. But the leaderboard is showing our average age-grade as 53.61%. 

https://challenge.fingerlakesrunners.org/Course/233198/Team

I suspect that it's averaging all efforts for the top 10 runners, rather than just the best effort. That's undesirable because it penalizes fast runners if they run easy efforts along with their fast times.

Acceptance criteria:
* The average age grade calculation for teams should count only the highest age-graded effort for each of the top 10 runners. Note that that's different from the top 10 age-graded _efforts_ because it's entirely likely that one runner will have several of the best efforts, but each person gets to contribute only one effort to the 10 that are used for the calculation. That way, a team needs 10 fast runners, rather than one person who could run 10 fast times.
* Secondary criteria: the 50-59 team should retake its rightful position at the top of the standings. :-)

**Comment by stevedesmond-ca** [comment]
Looks like it's sorting the athletes by their fastest time, but not their individual runs, so it's instead picking their first run (e.g. your 8:15) rather than their fastest (e.g. your 5:49)

Should be an easy fix, will have something out within the hour.

**Comment by stevedesmond-ca** [comment]
Fixed as of b28d466
