### ISSUE TITLE
Per-race most efforts results page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#4]
As a slow-but-steady competitor, I want to be able to check my standing against other competitors for most number of efforts.

Acceptance criteria:
- The results list should include rank, name, age, team, and number of efforts.
- The list should include all runners who have completed the course at least once.
- The page should display the total number of efforts across all runners.
- The page should display the total number of miles run across all runners. (Efforts times distance.)
- The page should display what the current average number of efforts is.
- The list should be sorted by number of efforts, with the largest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort)

**Comment by stevedesmond-ca** [comment]
What's our tiebreaker if 2 runners have the same number of efforts? Fastest time? Average time?

**Comment by adamengst** [comment]
I think we should use average time to order them. There's no harm in walking your dog every day on a course to try to win it, but if multiple people are going to do that, let's reward the person with the faster average.

That said, if there's an actual tie, I'll probably give them both a prize.

**Comment by stevedesmond-ca** [comment]
Implemented as of abcda14
