### ISSUE TITLE
Add Participants link to the top nav bar

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#42]
As a participant, it would be nice to know who else is running the Challenge, but there's no overall list, especially since some people have signed up but not yet submitted a result to Webscorer. I could imagine a snazzier solution (where everyone's name would be hotlinked to their results) later on, when it's unlikely that someone would have signed up but not submitted any results, but for now, the easy solution to this request is to add a Participants link to the top nav bar and point it at https://www.webscorer.com/registerlist?pid=1&seriesid=230582

Acceptance criteria:

* It's easy to see a list of all participants from the leaderboard

**Comment by stevedesmond-ca** [comment]
I think I can get the "start list" from the API using the series ID, in which case this can be more integrated --I'll take a look and see what I can figure out.

**Comment by adamengst** [comment]
That would be snazzier, as noted!

**Comment by stevedesmond-ca** [comment]
:sweat_smile: Of course it's not that simple, the athlete page crashes because it expects everyone to have at least one result -- should have something ready by tonight!

**Comment by adamengst** [comment]
Because who would sign up but not submit a result? :-) I'm seeing more people submitting, and it's all looking good so far.

**Comment by stevedesmond-ca** [comment]
Also have our first non-binary user, so I'll need to keep an eye on once they start competing -- found and fixed one crash around that already.

**Comment by adamengst** [comment]
I noticed them, but wasn't going to say anything until they posted a result. I may have to suggest to Vesa that Webscorer switch from F/M in its display to O for Other to match the option name.

**Comment by stevedesmond-ca** [comment]
Implemented as of daa7498

**Comment by adamengst** [comment]
Can you add a count that totals the number of people listed so there's an easy number to read? This falls into the category of surfacing cumulative data as I mentioned in the forum.

**Comment by stevedesmond-ca** [comment]
Yep, good idea -- done!
