### ISSUE TITLE
Anchor link to the Challenge Rules

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#43]
As a participant, I'd expect the Rules link in the nav bar to link directly to the rules, not the Challenge page in general. (Obviously, we didn't have a better link before! :-)). That link can now change to:

https://fingerlakesrunners.org/challenge/#rules

Acceptance criteria:

* A click on Rules should jump directly there.

**Comment by stevedesmond-ca** [comment]
Implemented as of 2210929
