### ISSUE TITLE
Add Stats page that pulls together cumulative per-course and overall stats

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#45]
As a race director, I'm interested in showing the community what it has accomplished overall in the Challenge, and as a participant, I want to see which courses are the most popular at a glance.

A Stats page could bring together a variety of cumulative data in this vein. At the moment, I'm not sure if any speed-related metrics make sense in such a page.

Acceptance criteria:

* A single bookmarkable page, linked from the nav bar (which is getting busy, hmm)
* Overall stats should include:
  * Total number of participants (overall, and separated by M and F)
  * Total number of runs completed (overall, and separated by M and F)
  * Total number of miles run (overall, and separated by M and F)
  * Average number of efforts (overall, and separated by M and F)
* Per-course stats should include (the same as above, I think):
  * Total number of participants (overall, and separated by M and F)
  * Total number of runs completed (overall, and separated by M and F)
  * Total number of miles run (overall, and separated by M and F)
  * Average number of efforts (overall, and separated by M and F)

**Comment by stevedesmond-ca** [comment]
Implemented as of a4b4d64

**Comment by adamengst** [comment]
Just a wee problem of too much precision. :-)

![image](https://user-images.githubusercontent.com/36641103/109727306-1a2c2e00-7b82-11eb-8a08-1c2b5fd17e41.png)

**Comment by stevedesmond-ca** [comment]
Arg, floating point: it was fine when it was 98!
