### ISSUE TITLE
Time of day off by 5 hours

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#46]
As per https://forum.fingerlakesrunners.org/t/time-of-day-off-in-webscorer/1761?u=adamengst it seems that the time of day we're getting from the API isn't honoring the GMT-5 timezone that's set for each of the races in Webscorer, and that Webscorer is displaying in its own results.

Acceptance criteria:
* The time stamp for each run should match with the time of day it was done in the Eastern time zone.

**Comment by stevedesmond-ca** [comment]
Fixed as of 93b7f36

**Comment by stevedesmond-ca** [comment]
Ooh, I see it now -- the production server doesn't have a time zone set, so it's defaulting to GMT/UTC. I'll hardcode it to our local time zone.

**Comment by stevedesmond-ca** [comment]
FIxed for real now as of 0972f80
