### ISSUE TITLE
Change copyright date to 2021

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#48]
It feels odd to have the copyright date in the footer be last year; let's update it to this year. I think the odd feeling comes from the fact that the site is updating all the time. It's probably easiest to tie it to the year of the last content or code update.

Acceptance criteria:
* The date be in the current year.

**Comment by stevedesmond-ca** [comment]
lol, that probably came in as part of the initial template -- updated as of 1e3951e
