### ISSUE TITLE
Indication of changes in standings

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#5]
As a competitor, I'd like to be able to tell when I've moved up or down in the rankings for any contest.

As the race director, I'd like to be able to identify significant changes in rankings to make it easier to write a weekly recap.

I'm not entirely certain what the acceptance criteria should be here yet, and I'd like to talk it through a little with you guys. From the runner standpoint, I'm thinking that perhaps people would like to see on a daily basis if their rank had moved up or down from the previous day. That might be because you ran another effort or a faster time, or it might be because someone else either ran an effort or a faster time, or that someone who was faster joined the race and entered their first result (which could push someone down). Obviously, the results would be live and would be changing throughout the day, every day, as new results come in, but it feels too granular to indicate whether an individual's rank has changed since the last result or not. If nothing else, the runner doesn't have much insight into what others do, so indicating changes at midnight, say, would provide a consistent reference point.

From the race director standpoint, the daily changes are mostly noise, but on a weekly basis (with the week ending Thursday at 11:59 PM, perhaps, so it could be recapped on Friday and everyone could plan for their weekend runs), I'd like to know which individuals and teams have moved in the standings, with a focus on who's in the top five in any contest (three are important, but the next two make it obvious who has fallen out of the top three). This could theoretically be as simple as a snapshot that's made every Thursday night at 11:59 PM and emailed to me so I could compare it against the previous week.

Does this sound helpful/reasonable?

**Comment by stevedesmond-ca** [comment]
The results have a "start time" on them, so it'll be easy enough to determine new results, or to show/compare "snapshots" as of a certain time, for a weekly report, etc.

I'm wondering if maybe just making any new results within the past 24/48/72 hours bold (or some other easy indicator) might be better (less noisy) than marking everyone with up/down icons. I guess I don't have much of an idea of how many attempts per day we're expecting on a given course -- that might influence the best way to show changes...

**Comment by adamengst** [comment]
Yeah, it's hard to say how it will work 

My gut feeling is that weekdays might be a bit slower, but that weekends could have a lot of efforts posted. What's hard is that you wouldn't need to do anything to have your ranking decrease (an increase would be less likely, or perhaps even impossible) if someone else runs a faster time or notches another effort. So you might want to know that you fell in the standings because you skipped a chance for a run.

We could simply table this for now and wait until we see how it works in real life. For my weekly recaps, I could just take some screenshots each week to refer back to the next week to start.

**Comment by stevedesmond-ca** [comment]
I have some ideas for how this could work, but we'll need to wait until we get some real data to see how it actually plays out. If you're OK with the screenshot approach for the first couple weeks, I'll see what sort of ad-hoc reporting I can pull together around mid-January.

**Comment by adamengst** [comment]
Totally fine to wait until we see how it's working!

**Comment by SteveDesmond-ca** [comment]
@adamengst With the latest additions of personal and course activity logs now live, do you think that's sufficient to be able to pick out any noteworthy changes in a given week, or should we still keep this idea of indicators on the data tables themselves in our back pocket?

**Comment by adamengst** [comment]
Yeah, I think we can close this one. Most of the categories don't really change that much, and the one that does (Most Miles) is usually pretty obvious. And I have no indication that individuals are interested that they went from 15th to 14th on some particular day.
