### ISSUE TITLE
Add Activity page that shows a log of who has done what

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#51]
Speaking as someone who has been watching the leaderboard like a hawk and enjoying it immensely, it would be nice to be able to see at a glance what everyone has been up to. For instance, today I noticed that Adam Pacheck and Ved Gund ran Pseudo Skunk, but I had to figure that out by realizing that their point scores had increased a lot and then going to look at the Pseudo Skunk results. This idea came up while talking with Heather Cobb after her Pseudo Skunk this morning (it's not just me!). Could we create an Activity page that just shows who has done what, newest at the top, for the last week? That would also throw some light on the slower runners who aren't likely to ever appear on the main page. I don't think it needs to go back forever, although if that's just as easy without performance issues, I'm not opposed.

Acceptance criteria:
* New page with its own URL
* Link in the nav bar (yeah, I know it's getting crowded, so we may have to think about that)
* Table of data showing each run for the past 7 days, newest at the top with sortable columns for:
  * Date and time
  * Athlete name
  * Course name
  * Time
  * Team (waffling on this last one; might be too much/not helpful)

**Comment by stevedesmond-ca** [comment]
To solve the navbar problem, what are your thoughts on grouping them into a "Reports" dropdown, similar to "Races"?
![image](https://user-images.githubusercontent.com/195896/109709524-9fa3e400-7b6a-11eb-872e-dea3401c210b.png)
I can't really think of a better name than "Reports" right now, but when the weekly/monthly comparisons for #5 come around, my assumption is that they'd go in here too.

**Comment by adamengst** [comment]
I think that's a fine solution, since everything can be bookmarked nicely if someone wants to go to a particular sub-page regularly. Though it should probably be Activity Log, Participants, Statistics for alphabetical order since it's not clear there's a functional order that should override.

While we're talking about the nav bar, the two things that occasionally niggle at me are:

* The word "Leaderboard" in the nav bar, since it feels like the whole site is the leaderboard to me. I get that it's the discoverable version of "go to the main page" so people don't have to guess at clicking the logo, like experienced users would do, but it still feels a little off, especially when on the main page itself, where it's self-referential. One solution here might be to have it disappear on the main page only.
* While I like the Rules link, and like that it points directly to them rather than the main Challenge page, which starts with general description, it does feel a little odd to not have an explicit About link that goes to the Challenge page. A possible solution here would be to make an About menu that would contain "FLRC Challenge" pointing at the top of that page, "Rules" pointing at the rules anchor link, and "Timing" pointing at the timing instructions anchor link. That keeps the alpha sort even if Timing comes before Rules on that page.

@scottpdawson, any thoughts here from your UX perspective?

**Comment by stevedesmond-ca** [comment]
One thing I was wondering when trying to fit everything in, is "Home" better than "Leaderboard"?

**Comment by adamengst** [comment]
I was thinking the same thing and was merely wondering if that felt too 1990s. :-) But yes, it's probably the better term.

**Comment by stevedesmond-ca** [comment]
Implemented as of a4b4d64

**Comment by scottpdawson** [comment]
Ha! See what happens when I'm working? You guys do great work. I love the updates, Steve.
