### ISSUE TITLE
Waterfront Trail and Cornell Botanic Gardens raceIDs changed in Webscorer

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#53]
Hey @stevedesmond-ca, can you update the leaderboard with the new raceIDs that Webscorer changed on us? The proper IDs are:

Waterfront Trail: 235665
Cornell Botanic Gardens: 235658

Thanks!

**Comment by stevedesmond-ca** [comment]
I thought it was fishy that no one had run them yet -- I would have noticed this afternoon, planning on a pair of arboretum loops!

Updated in 6c5e9d3.

**Comment by adamengst** [comment]
Yeah, I'm not sure what's going on, since I was pretty sure my test results were still in there holding the place. Perhaps Webscorer sees it as a different race because my test results were so long ago. Next up will be South Hill Rec Way, and I'll do a test post when I install the sign so we can see if this happens ahead of time.
