### ISSUE TITLE
Update raceID for the South Hill Rec Way course

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#57]
The new raceID for South Hill Rec Way, which is now live, is 236137

https://www.webscorer.com/race?pid=1&raceid=236137

Thanks!

**Comment by stevedesmond-ca** [comment]
Updated as of 7f2842d

**Comment by adamengst** [comment]
Oh, sorry, forgot to mention. Could you also change its distance from 7 miles to 6.8? I'm not 100% sure of that (just using online mapping), but it's really not 7.

**Comment by stevedesmond-ca** [comment]
Updated as of 2043eae
