### ISSUE TITLE
Rounding code is sometimes  incorrectly rounding up entries with 0 in the tenths place

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#58]
Yesterday, I ran the Cornell Botanic Gardens course in 16:17, and entered 16.17.0 into Webscorer manually. I verified that that's the time in the Webscorer results.

![image](https://user-images.githubusercontent.com/36641103/111910298-2d227780-8a37-11eb-8004-595bb48c654f.png)

However, when I look at the leaderboard, it's reporting my time as 16:18.

![image](https://user-images.githubusercontent.com/36641103/111910324-4aefdc80-8a37-11eb-8df2-4284f0afb62e.png)

Oddly, I entered my second run yesterday as 16:43, and that one came through correctly from Webscorer to the leaderboard. Perhaps it's different because it's not my fastest?

![image](https://user-images.githubusercontent.com/36641103/111910360-71ae1300-8a37-11eb-9f6d-e6478eb17a61.png)

My suspicion is that the code is sometimes applying the rounding rule that says if the tenths of seconds are non-zero, to round up to the nearest whole second even when the tenths are 0.

I think I've seen this happen elsewhere... yes, look at Rich Heffron's fastest time from the East Hill Rec Way. It was entered at 4:39 but appears as 4:40.

Acceptance criteria:
* Results on the leaderboard should match Webscorer whenever the tenths place is zero.

**Comment by stevedesmond-ca** [comment]
My guess without looking at the code or data yet (so I don't forget) is that the app isn't replacing the hundredths/thousandths digits, only up to tenths -- e.g. 3.459 seconds for the manual start/stop required to edit a time gets saved as 16:17.059 once edited... Will need to floor the decimal before the ceiling by whole seconds.

Either that or more floating point nonsense😒

**Comment by stevedesmond-ca** [comment]
Yep, Webscorer changed something about their API responses and your 16:17.0 is coming through as `977.0071390151977` seconds (previously would have been `977.0`) -- I'll update the code to truncate to a single decimal point before doing the ceiling to match USATF rules

**Comment by stevedesmond-ca** [comment]
Fixed as of c05a3ec

**Comment by adamengst** [comment]
Oh, interesting. Good sleuthing. I would have expected them to rewrite the time entirely rather than just replace digits.
