### ISSUE TITLE
Timestamps on results are 1 hour earlier than they should be

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#59]
Stupid DST. The timestamps we're displaying in the leaderboard are for standard time, not daylight saving time, and are thus 1 hour earlier than they really took place. Webscorer's public results pages are correct.

![image](https://user-images.githubusercontent.com/36641103/111922398-f2890100-8a6f-11eb-81c1-ae03127b079e.png)

![image](https://user-images.githubusercontent.com/36641103/111922413-05033a80-8a70-11eb-9fb0-52e3c286a71a.png)

Acceptance criteria:

* Times match the times shown in the Webscorer public results

**Comment by stevedesmond-ca** [comment]
Fixed as of 64cec4c -- should display correctly automatically in November once DST ends.
