### ISSUE TITLE
Per-race team standings page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#6]
As a team member, I want to be able to see where my team is for any given race:

Acceptance criteria:

* The page should list each of the seven teams (one for each age group).
* For each team, the list should include rank (based on lowest total points), name, average age-grade for the top 10 runners, points for the age-grade contest (1 to 7), number of total team efforts, points for efforts (1 to 7), and total number of points (age-grade points plus most effort points).
* The list should be sorted by points, with the smallest number at the top, but be sortable by clicking column headers (click once to sort, click a second time to reverse sort).

**Comment by stevedesmond-ca** [comment]
Are there single-gender (M/F) teams as well, or are we just doing one combined team?

**Comment by stevedesmond-ca** [comment]
Since age grade values are strictly-gendered, if a non-binary runner is in the top 10 for their team, use the male age grade (since that would provide a more conservative value?)

**Comment by stevedesmond-ca** [comment]
Should most runs be averaged over the number of runners on a team? e.g. a team of 2 who each run 10 times would have less than a team of 11 each running 2 times.

**Comment by adamengst** [comment]
> Are there single-gender (M/F) teams as well, or are we just doing one combined team?

No, teams don't worry about gender because age-grading theoretically levels the playing field with both age and gender, and the most efforts competition doesn't care.

> Since age grade values are strictly-gendered, if a non-binary runner is in the top 10 for their team, use the male age grade (since that would provide a more conservative value?)

Yes, I think that makes sense. I suspect it would be a vanishingly small edge case, since to my knowledge, we've only once had a non-binary runner in a race (literally one person in one race), and they weren't fast.

> Should most runs be averaged over the number of runners on a team? e.g. a team of 2 who each run 10 times would have less than a team of 11 each running 2 times.

My feeling is no, most efforts should be a raw number, not an average. The reason is that we want people to recruit others to their teams, and the main way to incentivize people to recruit slower runners is on the raw number of efforts, where each slower runner could be valuable if they run a lot.

**Comment by stevedesmond-ca** [comment]
Implemented as of 2443630
