### ISSUE TITLE
Per-course points and age grade on athlete page

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#60]
As a runner gunning for the overall points or age grade competition, I want to see my points and age grade for my fastest run on each course all in one place, so that I can easily tell my best/worst courses and where I can most improve.

Acceptance criteria:
- athlete page shows points and age grade for each course alongside fastest time

Note:
- table should probably pivot with this additional data

**Comment by adamengst** [comment]
Sorry, somehow didn't get a notification of this one.

I think this is a great addition.

**Comment by stevedesmond-ca** [comment]
Implemented as of 51e8ee7
