### ISSUE TITLE
Merge teens into 20-29 and 70+ into 60-69

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#64]
Given the low numbers in the teen team and the 70+ team, it makes sense to merge them into nearby teams.

Acceptance criteria:

* Everyone currently in the 1-19 team will be included in a new 1-29 team.
* Everyone currently in the 70+ team will be included in a new 60+ team.

**Comment by stevedesmond-ca** [comment]
Implemented as of c5a26f9
