### ISSUE TITLE
New URLs for Timing and Rules

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#67]
I refactored the FLRC Challenge Web pages since the page was getting too long and there were too many haphazard sub-pages. The URLs to link to for the leaderboard nav bar links for Timing and Rules are now:

https://fingerlakesrunners.org/challenge/timing/
https://fingerlakesrunners.org/challenge/rules/

Acceptance criteria:
* Links from the leaderboard nav bar go to the new pages

**Comment by stevedesmond-ca** [comment]
Implemented as of 19d15ba
