### ISSUE TITLE
Group the activity log rows by date range

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#69]
As an RD, I want to more easily see when people have run, so that I can better pull out results to remark upon.

Acceptance criteria:
- activity log is split up into 2 tabs
   - Recent
   - Archive
- Recent tab will show all results for the past 31 days, broken up into sections (with headings) for
   - Today
   - Yesterday
   - This Week (2-7 days ago)
- Archive will show all results, broken down into sections for each calendar month

**Comment by stevedesmond-ca** [comment]
Implemented as of a496783

**Comment by stevedesmond-ca** [comment]
Ugh, timezones...

**Comment by adamengst** [comment]
Timezones are a bear, but at least we're all in the same one.

I'm not seeing this yet, so I assume you haven't deployed yet. (I was just getting around to coming here to add it and you've already implemented! :-) )

**Comment by stevedesmond-ca** [comment]
I deployed it last night and immediately noticed the mismatch so rolled back -- debugging now with my laptop's timezone set to UTC, hopefully can go live tonight but one of the 2 bugs only shows itself after 8pm (12am GMT) so we'll need to see if that one's solved then too!

**Comment by stevedesmond-ca** [comment]
Fixed as of c0fa21f
