### ISSUE TITLE
Athlete page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#7]
As a competitor, I'd like to see a summary of how I'm doing across all races so I don't have to check each one separately:

Acceptance criteria:
* The page should list the athlete's name, age, and team.
* Display of the total number of points in the Challenge and ranking
* Display of the total number of efforts in the Challenge and ranking
* The runner's team's ranking in the Challenge
* Each race should be an item in a list and should include:
  * Fastest time and rank within the race
  * Fastest average time and rank within the race
  * Total number of efforts and rank within the race

**Comment by stevedesmond-ca** [comment]
Do you see users as being able to log in so it knows who they are? Or just find themselves either on the results or via a search box?

**Comment by adamengst** [comment]
No, I don't see any reason for people to have accounts and need to manage logins and the like. That's a rathole.

If each person simply gets an automatically generated athlete page, they can bookmark it to come back to at any time, and anyone else can see it too, which might be useful when researching the competition. :-)

**Comment by stevedesmond-ca** [comment]
Are all of the rankings to be shown here gendered? (except total miles (vs total efforts above) since that competition is combined)

**Comment by stevedesmond-ca** [comment]
Implemented as of cb4e9c2

**Comment by stevedesmond-ca** [comment]
(wrong button, still needs additional testing)

**Comment by stevedesmond-ca** [comment]
Tests added
