### ISSUE TITLE
Add history to Statistics page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#71]
As a race director, I like to see the cumulative efforts of the participants in the FLRC Challenge. To that end, it would be helpful (and reduce the amount of manual calculation) if each of the time segments in the Activity Log could be followed by a totals row that would summarize what that segment encompasses. Since the data is quite different than the columns shown, it probably shouldn't try to be part of the table itself.

Acceptance criteria:
* Under each time segment (Today, Yesterday, This Week), have a line that shows:
  * Number of efforts
  * Number of unique efforts (not as sure about this; but sometimes people do a lot of repetitions, which feels different)
  * Total miles run
  * Total time on feet
* Below the This Week summary, have another line that's cumulative for all three time periods with the same categories. This is the one I'll look at each week when writing the recap.

**Comment by stevedesmond-ca** [comment]
Could we put this on the statistics page instead?

Feels like it makes more sense there, and it could be based around a consistent week (Sat-Fri?) so you wouldn't just be out of luck if you accidentally missed a recap by 1 day.

We could even have the history of all the requested data for each week, for easy (external) charting.

**Comment by adamengst** [comment]
I like it! Yeah, it just felt like a summary of what we were showing, but the fact that the summaries are different from the columns that show in the Activity Log is indication that the Statistics page would be better.

**Comment by adamengst** [comment]
Cool beans!

**Comment by stevedesmond-ca** [comment]
Out of time for this afternoon, but hoping to land this around 8pm if you wanted to wait until then for the weekly recap!
![image](https://user-images.githubusercontent.com/195896/121732359-26e4ea00-cac0-11eb-93d9-540b916a3aeb.png)

**Comment by adamengst** [comment]
Looks great! Maybe I'll tease it if I release earlier.

What does Average Runs mean in this context? Average runs per person?

**Comment by stevedesmond-ca** [comment]
Implemented as of eeeb0cc
