### ISSUE TITLE
Add obvious visual indicators when age grade >100%

### ISSUE THREAD

**Issue by stevedesmond-ca** [FingerLakesRunnersClub/ChallengeDashboard#73]
As an RD, I want invalid results to pop out, so I don't need to do as much digging to find out why everyone's scores got messed up.

Acceptance criteria:
- results rows in the "fastest" table are highlighted in red if the age grade is >100%
- a message is displayed at the top of the athlete's page about invalid results, so they might have a better chance of spotting it themselves

**Comment by stevedesmond-ca** [comment]
Upon further playing with the data, and considering how much this is coming up, I think a better course of action is to not count an athlete's invalid result from a course until it is fixed. (where invalid = age grade >100%)

This way, they are the only one affected by the data entry error -- right now, everyone's overall points are thrown off because the change in points for a single course rearranges many rankings/positions, depending on who's run that course and how fast they ran.

We would probably need to make it much clearer from the athlete info page that their invalid result needs to be fixed.

Thoughts, @adamengst?

**Comment by adamengst** [comment]
I see what you're saying, and I agree that it would be better not to throw everything off until I get the spurious data fixed.

The real question is how we're alerted. Right now, I see something weird, like Adam Pacheck not having a clean divisible by 100 score, and that makes me dig further.

Could you mark a result as questionable throughout? For instance, by displaying it in red?

**Comment by stevedesmond-ca** [comment]
It'd be easy enough to do something like this:
![image](https://user-images.githubusercontent.com/195896/121587409-c5127a80-ca02-11eb-9795-a1bbba0fd57c.png)

But the onus is still on you to get all the data right so no one else is mixed up.

If we just remove the record, we could always (in addition to showing it on the athlete's page) add a "hidden" page with invalid results so you can still check in from time to time and proactively poke people to fix their data, but it wouldn't be nearly as urgent because everyone else would still be good. This puts the onus on the athlete to fix their own data, so they can get the points they deserve.

**Comment by stevedesmond-ca** [comment]
This was a little more complicated than expected, but I think we're ready to go live with it tonight. Not sure if you wanted to include a note with the weekly recap about the change, since it really only affects a small subset of users (those who submit invalid times) but here's the basic workflow:

If a user notices a drastic decrease in their overall points, or if they check their athlete page for any other reason when they have an invalid result (where an invalid result has an age grade > 100%), they'll see the following:
![image](https://user-images.githubusercontent.com/195896/122599937-18a54980-d03d-11eb-893f-68010c8659a6.png)

The "Invalid Results" page shows invalid results for any courses that have them, or a happy green message if there aren't any:
![image](https://user-images.githubusercontent.com/195896/122600189-6a4dd400-d03d-11eb-8668-afbb0d4afddb.png)

The "View All Runs" list from the athlete's page will also show their invalid result(s) for that course, at the top with a rank of 0.

**Comment by adamengst** [comment]
Looks good! I'll mention it briefly in the recap...

**Comment by stevedesmond-ca** [comment]
Implemented as of 7ff6346
