### ISSUE TITLE
Twiddle cache to pick up changed name

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#74]
Perhaps this will happen automatically when you deploy next, but if not, could you tweak the Participants list so Michael Sullivan is reloaded from Webscorer? I fixed his name there, but it's not yet reflected on the leaderboard a few days later.

![image](https://user-images.githubusercontent.com/36641103/122612459-282e8d80-d051-11eb-8011-d084a15619b1.png)

**Comment by stevedesmond-ca** [comment]
Yes, tonight's deploy will start a fresh container
