### ISSUE TITLE
Group page capability that brings together an arbitrary set of runners

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#75]
As race director, I'm interested in bringing more people into the Challenge and one way to do that is to let a group of people compete against each other. That might include the Cayuga Medical Sports Medicine department, for instance. Different groups could also compete against one another (Sports Med vs Physical Therapists, for instance). The idea is that the page could be sorted in different ways to see who was in the lead for different metrics.

Acceptance Criteria:

* A single page with a unique URL that would list all the people manually specified in the group (they can't be identified automatically, and someone could be in multiple groups).
* Sortable columns for
  * Name
  * Age
  * Courses Run
  * Average Age Grade (to level the playing field)
  * Overall Points (to pull out fastest)
  * Overall Miles (to pull out most miles)
  * Number of efforts (maybe; if it's different from Most Miles for calling out dedication)

**Comment by stevedesmond-ca** [comment]
Ooh, I just figured out how we can do this more dynamically, so we don't need to edit the app's config every time a new group/member gets added/removed:
- have a URL segment on the FLRC site that contains the list of groups and their members' athlete IDs (e.g. https://fingerlakesrunners.org/challenge/groups displays `{ "CMSM": [98734, 3248, 98456, 34565], "CMPT": [82374, 293847, 293847, 987234] }`) -- I think these are available from WebScorer's front-end, but if not I can show you how to get them from their API...are you familiar enough with JSON like the above that you'd be able to maintain this list?
- the leaderboard will look up the list of athletes for a given group from the FLRC site API (I already checked and [it's on](https://fingerlakesrunners.org/wp-json/wp/v2/pages)) with the matching URL (e.g. https://challenge.fingerlakesrunners.org/groups/CMSM, https://challenge.fingerlakesrunners.org/groups/CMPT, etc)

**Comment by adamengst** [comment]
Oh, clever. I hadn't thought about using the FLRC site as a go-between for largely static config, largely because I don't quite think of it as "mine" in the way I do other sites. I'm not particularly familiar with JSON, but I'm highly trainable and figure things out quickly, so I strongly suspect I can maintain it. :-)

So in essence, I'd just maintain the group on the FLRC site and the leaderboard would query that whenever necessary.

**Comment by stevedesmond-ca** [comment]
Quick JSON (JavaScript Object Notation) primer:
- `{ }` encloses an object, which can contain zero or more comma-separated `"field name": value` pairs
- `[ ]` encloses an array, which can contain zero or more comma-separated values
- field names must be a `"string"`, including the quotes
- a value can be a `"string"`, `1234.56` (number), `{ "other": "object" }`, or `[ "array" ]`
 
If you create a page with the following as its content:
```json
{
    "Test": [ 6728, 115406 ]
}
```
This will create an object that contains a test group (with a key/name of `"Test"`) that includes the IDs for me and you in it. Feel free to add additional groups if you already know who's in them.

Once I know the URL I can start programming/testing against it.

**Comment by adamengst** [comment]
I'm not sure how the WordPress wrapper comes into place, but see if this is usable.

https://fingerlakesrunners.org/challenge-groups/

I can change URL or content, but I don't offhand know how to get a bare page in WordPress. Perhaps making a file via FTP...

**Comment by stevedesmond-ca** [comment]
Almost there!

Can you see if there's a "remove formatting" button when you select all the JSON in the admin view? You may just need to change the fancy quotes (“ ”) into normal quotes (" ") manually if not.

**Comment by adamengst** [comment]
Alas, there's no manually applied formatting—that's the WordPress theme automatically curling quotes.

I'll have to see if I can figure out how to connect via FTP and make a static file. If that doesn't work, we'll ask Eli.

But I'm feeling under the weather again and way behind on other things so it may not be for a day or two.

**Comment by stevedesmond-ca** [comment]
Yep, no rush -- worst case scenario I can do some cleanup on the import side before parsing it

**Comment by stevedesmond-ca** [comment]
Yep, no rush -- worst case scenario I can do some cleanup on the import side before parsing it

**Comment by adamengst** [comment]
Can you work with this URL, say? I created it as a static page via SFTP so it's outside the WordPress manipulations.

https://fingerlakesrunners.org/wp-content/uploads/challenge-group-json.html

**Comment by stevedesmond-ca** [comment]
Even better! (as long as that's not too much trouble to maintain)

Let's rename it `challenge-groups.json` (`.json` is the standard extension for JSON) so the MIME type gets picked up correctly, and then we should be good to go!

**Comment by adamengst** [comment]
Done! (I was thinking that when I named it, but wimped out and went with HTML to avoid potential WordPress config issues with other extensions.)

https://fingerlakesrunners.org/wp-content/uploads/challenge-group.json

**Comment by stevedesmond-ca** [comment]
Are these going to be mixed groups, or split M/F? If the former, I don't know that overall points will be possible to show, unless we add the "All/F/M" filter that's available elsewhere/throughout, but I don't know if that would make sense depending on how small these groups will be. Plus it's kind of an apples/oranges comparison, e.g. I'm about as fast as the 3rd-5th place women, but they have 200+ more points because their overall competition is closer.

**Comment by adamengst** [comment]
I imagine they'd be mixed groups, so yeah, let's drop overall points. What about a total time number? That might be a nice way to reward the slower and more dedicated runners.

**Comment by stevedesmond-ca** [comment]
Looks like we've got a little too much data to fit this in at the widest width (where we can't use the horizontal scrolling)
![image](https://user-images.githubusercontent.com/195896/124643907-a5367100-de5f-11eb-9d73-e28fde3dc500.png)

Is there a least-useful field here that we could drop? The view and a lot of the logic is shared with the "Team Members" list since they're pretty much the same thing, so any changes would also show up there.

Alternatively, if shortening some of the column headers still makes things clear enough, we can fit everything in that way.
![image](https://user-images.githubusercontent.com/195896/124644143-ed559380-de5f-11eb-9f25-02bfa8749c7f.png)

Thoughts?

**Comment by stevedesmond-ca** [comment]
Looks like without a not-insignificant re-architecting, it's an either/or of age grade or total time right now...maybe if we want to include that as a metric, we can create a separate issue to track that?

**Comment by stevedesmond-ca** [comment]
@adamengst The initial iteration of this is now live -- give it a try at https://challenge.fingerlakesrunners.org/Group/Index/Test and let me know what you think.

You can then add a new group to the JSON file and change the URL accordingly with that group's name instead of "Test" to see that one.

**Comment by adamengst** [comment]
Woo, I like it! Some answers/issues:

* I created a CayugaMed group in the JSON file, but it doesn't seem to show up at https://challenge.fingerlakesrunners.org/Group/Index/CayugaMed or https://challenge.fingerlakesrunners.org/Group/Index/HighNoon
* Can we have spaces in the group names? %20 encoding in the URL? Not a big deal either way.
* I'm not sure where we're at on fitting in Total Time. Is it just a matter of shrinking the labels? If so, Category could become Sex, and Average Age Grade could become Age Grade.
* I wonder if Rank might be the easiest to drop, since it becomes irrelevant with any sort.

**Comment by stevedesmond-ca** [comment]
If you replace each `}{` pair between the groups, it should work:
```
{
    "Test": [ 6728, 115406 ],
    "Cayuga Med": [ 131613, 116441, 97901 ],
    "High Noon": [ 6728, 41357, 74963, 73461, 73397, 54661, 73179, 35364, 49461, 38756, 19858, 122628, 127288, 36492 ]
}
```

Adding spaces in the names should be fine, but I forget if it's `%20` or `+` in the URL to have ASP.NET translate it out of the box.

**Comment by adamengst** [comment]
Ah! Fixed now.

Turns out spaces in the JSON name are just dropped, so the URL and the group name both appear without a space.

**Comment by adamengst** [comment]
You're probably doing something on the server, but no changes to the JSON are taking right now. I've added Sarah Ridenour to the CayugaMed group, but it's not displaying her. And no additions or removals from other groups are taking either.

**Comment by adamengst** [comment]
And now it has caught up

**Comment by stevedesmond-ca** [comment]
Yeah, if the FLRC site is on wordpress.com, it might take a minute for the JSON updates to propagate over their CDN.

I'll see what I can do about the spaces in the names/URLs.

**Comment by stevedesmond-ca** [comment]
@adamengst spaces in the group names should work now if you wanted to try renaming them...feel free to remove our test group as well

**Comment by adamengst** [comment]
Cool, looks like it prefers %20 in the URL.

https://challenge.fingerlakesrunners.org/Group/Index/High%20Noon

**Comment by adamengst** [comment]
Two questions from above:

* I'm not sure where we're at on fitting in Total Time. Is it just a matter of shrinking the labels? If so, Category could become Sex, and Average Age Grade could become Age Grade.
* I wonder if Rank might be the easiest to drop, since it becomes irrelevant with any sort.

**Comment by stevedesmond-ca** [comment]
If that's a valuable metric to have, it's going to be a somewhat significant reworking of some of the data flows, which was my thought behind splitting it off into its own issue, so we could get something 99% of the way there out now, and then we figure out how to squeeze it in once the actual data is available.

**Comment by adamengst** [comment]
Ah! OK, I just wasn't sure if it was more of a reworking or more of a layout issue. No worries, and Total Time can wait for now.
