### ISSUE TITLE
Add personal activity log to Athlete page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#80]
As the race director with the need to report on what's happening in the weekly recaps, I'm having trouble keeping track of what people are doing and am spending a lot of time poring through the Activity Log and per-course View Runs lists. It would be helpful if there was a per-runner activity log on each person's Athlete page so I could see what they've done recently. (Or it could be linked from the Athlete page, if putting it at the bottom feels too cluttery.)

Acceptance criteria:

* On the Athlete page or a page linked from the Athlete page, add a table with the following data:
  * Date, Course, Time, Age Grade
  * Date should be the default sort, by most recent at the top
  * Columns should be sortable to reverse the date, collect courses together, and see which efforts are best from an age-grading perspective.

**Comment by SteveDesmond-ca** [comment]
Implementing a "course activity log" will also be pretty trivial once this is in place

**Comment by SteveDesmond-ca** [comment]
Excellent use case: @scottpdawson just blew past me into 6th place...how did that happen?

**Comment by SteveDesmond-ca** [comment]
(someone's been busy...)
![image](https://user-images.githubusercontent.com/195896/131253818-46d94ae0-95f3-40a3-8828-ceb1f6175fec.png)

**Comment by scottpdawson** [comment]
Ha! @SteveDesmond-ca, *you're* the one who's been busy. What you've built here is really something special. It's been incredibly motivating to have real-time feedback as soon as you're done with a race. Really impressive how you've been cranking out all these new features on top of what was already awesome.

**Comment by SteveDesmond-ca** [comment]
Implemented as of ab48afa

**Comment by adamengst** [comment]
Otherwise it looks great!

**Comment by SteveDesmond-ca** [comment]
Unfortunately, age grades are only available once raw results go through the "ranking" pipeline, and the global and course activity logs (which is really just a filtered global activity log) only use the raw result data.

The workaround is to select the person's name and then "View All Runs" for that course, but obviously that's 2 more clicks than if the data were right there. If you think having age grade here is particularly valuable, I can see about converting the course log to be more like the personal log (e.g. no "today/yesteday/this week" groupings) but I do have a slight concern that the more popular short courses might tank the server briefly, depending how long it takes to calculate that many age grades :grimacing:

**Comment by adamengst** [comment]
Oh, no, never mind. I was just thinking it looked a little data-sparse, and that age-grade would fill it out in a potentially useful way. Totally not important.
