### ISSUE TITLE
Create Completed page that lists those with all 10 efforts

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#81]
As the race director, with a need to acknowledge those who have completed all 10 courses, it's getting increasingly hard to figure out who has done so from the Age Grade page. I end up finding Heather at the bottom of those who have done 10 courses, trying to remember what number she was before, then looking up and trying to see who might be new. A dedicated page linked in Reports would be a huge help here.

Acceptance criteria:

* Create a new page linked from Reports that lists Completions
* The page should include only people who have completed all 10 courses
* The table should include the following columns:
   * Rank, Name, Age, Category, Average Age Grade, Date Completed (last one is a new thing)
   * Default sort should be by Date (to reward those who finished earlier) but all columns should be sortable

**Comment by SteveDesmond-ca** [comment]
Implemented as of 29979d1

**Comment by adamengst** [comment]
Now that I look at this, could we change the word "Completed" to "Completions" so it's parallel to everything else in the Reports menu?

**Comment by adamengst** [comment]
Oops! The Athlete links on the Completions page are all broken, with this URL:

https://challenge.fingerlakesrunners.org/Athlete/Index/undefined

**Comment by SteveDesmond-ca** [comment]
:see_no_evil: fixed in 0936836

**Comment by adamengst** [comment]
Almost! :-) The page title needs to change from Completed to Completions too.

![image](https://user-images.githubusercontent.com/36641103/131579581-f9f11fa5-357c-48f9-8631-83d1e135b6b4.png)

**Comment by SteveDesmond-ca** [comment]
Done, deploying now
