### ISSUE TITLE
Calculating individual points

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#9]
As a competitor gunning for the overall Challenge win, I want to know how many points every effort is worth. 

Acceptance criteria:
* To calculate points, the fastest time for any race shall get 100 points.
* Every slower result will the number of points that's proportional to how far back in time the result is from the leader. In essence, the result is a percentage of the fastest time and gets that number of points. (result divided by fastest time, multiplied by 100)
* This number will have to be recalculated on every result, since a new fastest time will push every result below it down.

**Comment by stevedesmond-ca** [comment]
How should this number be rounded? Whole numbers only? Single digit decimal?

**Comment by adamengst** [comment]
Let's go for two-digit decimal, based on some of what I've seen in the Stonehead rankings. So you could have 99.88 beating 99.86, whereas otherwise they'd seem to tie.

**Comment by stevedesmond-ca** [comment]
👍🏻 should I have age grades showing to 2 decimal digits as well for consistency?

**Comment by adamengst** [comment]
Yes, definitely. Age grades are always shown that way.

**Comment by stevedesmond-ca** [comment]
Implemented as of 175ab4c
