### ISSUE TITLE
Karen Ingall's Activity log won't laod

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#90]
When I go to Karen's page at:

https://challenge.fingerlakesrunners.org/Athlete/Log/122478

I always get an HTTP error 500.

![image](https://user-images.githubusercontent.com/36641103/147862873-fe6f3c79-553e-4b41-8483-781b916f6111.png)

I suspect it's due to how she manually uploaded a bunch of results in Cornell Botanic Gardens on the 30th, so it may be something odd in the Webscorer data. It is important that a fix not change her overall miles, though, since we need to preserve the tie.

**Comment by SteveDesmond-ca** [comment]
lol, she ran so many times she broke the app!

I can confirm that this bug only affects the display of the activity log for individual athletes who have more than 256 total runs throughout the year (of whom Karen is the only one) so any totals/numbers themselves should not be affected at all.

I'll get the fix out tomorrow when I have more brain power, but for now here's the HTML (zipped) for verification: [Karen Ingall — Activity Log — FLRC Challenge.zip](https://github.com/FingerLakesRunnersClub/ChallengeDashboard/files/7798413/Karen.Ingall.Activity.Log.FLRC.Challenge.zip)

**Comment by SteveDesmond-ca** [comment]
Fixed as of 6a88346
