### ISSUE TITLE
Add links to course names on Statistics page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/ChallengeDashboard#92]
As someone who's collecting stats on all the races, I find myself navigating between race pages regularly, and while I can use the menu at the top, whenever I'm on the Statistics page, it would be handy to be able to click the race name in the table to jump to that race's page in the leaderboard. Hopefully super easy to do...

**Comment by SteveDesmond-ca** [comment]
Implemented as of 9b0c9c8
